Reshaped
swift-numerics-workgroup/swift-shaped-array pull request #10
Opened 2022-12-26 02:02 UTC by KhalidAl-otaibi

Implemented reshaped #9

2022-12-30 17:54 UTC, rexmas commented on Sources/ShapedArray/Operators/Basic.swift
> +//
I'll add this to the readme, but we need to follow the same copywrite as in the other files. E.g. https://github.com/swift-numerics-workgroup/swift-shaped-array/blob/99c2f10036a42f66bead022f35d1030d1d39d677/Sources/ShapedArray/ShapedArray.swift#L1-L14

2022-12-30 17:55 UTC, rexmas commented on Sources/ShapedArray/Core/ShapedArray.swift
> +
It seems like you committed unnecessary whitespace in 2 places

2022-12-30 17:57 UTC, rexmas requested changes
Another question, why did we include a `Core` directory? we should separately discuss directory structure outside of this pr.

Thanks for doing this, didn't realize it'd be that easy, I'll jump on something else today :)

2022-12-30 17:59 UTC, rexmas commented
On a separate topic, i think we should put thought into our commit messages. My go to is to state "what" this does, and "why". Commit history like "Stuff" isn't useful, there's still time to squash all these commits however after adjustments have been made.

2022-12-30 18:00 UTC, rexmas commented
Oh, and let's include some unit tests too please

2023-01-03 10:36 UTC, JaapWijnen commented
The reshape function is unsafe at the moment I'd suggest adding some asserts to the function to check if the new shape is compatible with the old shape / available data

2023-01-08 18:03 UTC, rexmas commented on Sources/ShapedArray/Basic.swift
> +}
files should terminate with a newline

2023-01-08 18:05 UTC, rexmas approved these changes
just add the terminating newline and otherwise looks great!

2023-01-08 19:34 UTC, merged